/**
 * Strict structured JSON schema that the orchestrator must always return.
 */
export interface AssistantResponse {
  /** The final natural language response provided to the fan. */
  answer: string;
  /** The ID of the gate chosen, or null if no valid gates exist. */
  recommended_gate: string | null;
  /** Step-by-step route instructions for the fan. */
  route_steps: string[];
  /** Any relevant accessibility notes for the route. */
  accessibility_notes: string[];
  /** The calculated urgency level based on congestion and time to kickoff. */
  urgency_level: 'low' | 'medium' | 'high';
  /** Human-readable trace explaining why this decision was made (generated by logic, never LLM). */
  reasoning_trail: string[];
}
